### ISSUE TITLE
Can I upload an image to the album?

### ISSUE THREAD

**Issue by ordinarycas** [MaxfieldWalker/vscode-imgur#1]
How to upload images to a specific album？

This images is better management.

If can, How to set it?

**Comment by maxfie1d** [comment]
I will check it within about three days.

Stay tuned.

**Comment by maxfie1d** [comment]
I added album upload feature.

I'll publish new version of vscode-imgur soon!

**Comment by maxfie1d** [comment]
I just published vscode-imgur 0.0.3 with album upload support!

https://marketplace.visualstudio.com/items?itemName=MaxfieldWalker.vscode-imgur

**Comment by maxfie1d** [comment]
Fixed 1a1577474e7c724c164e6535a2dfd3f977e5b5a8.
